import 'package:flutter/material.dart';
import 'package:world_app/services/world_time.dart';


class ChooseLocation extends StatefulWidget {
  const ChooseLocation({super.key});


  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {
  int counter =0;


  List<WorldTime> locations = [
    WorldTime(location: 'Kenya',flag: 'kenya.png',t_url: 'Africa/Nairobi'),
    WorldTime(location: 'Egypt',flag: 'egypt.png',t_url: 'Africa/Cairo'),
    WorldTime(location: 'United Arab Emirates', flag: 'AE.png', t_url: 'Asia/Dubai'),
    WorldTime(location: 'Afghanistan', flag: 'AF.png', t_url: 'Asia/Kabul'),
    WorldTime(location: 'Antigua and Barbuda', flag: 'AG.png', t_url: 'America/Antigua'),
    WorldTime(location: 'Anguilla', flag: 'AI.png', t_url: 'America/Anguilla'),
    WorldTime(location: 'Albania', flag: 'AL.png', t_url: 'Europe/Tirane'),
    WorldTime(location: 'Armenia', flag: 'AM.png', t_url: 'Asia/Yerevan'),
    WorldTime(location: 'Angola', flag: 'AO.png', t_url: 'Africa/Luanda'),
    WorldTime(location: 'Antarctica', flag: 'AQ.png', t_url: 'Antarctica/Palmer'),
    WorldTime(location: 'Argentina', flag: 'AR.png', t_url: 'America/Argentina/Buenos_Aires'),
    WorldTime(location: 'American Samoa', flag: 'AS.png', t_url: 'Pacific/Pago_Pago'),
    WorldTime(location: 'Austria', flag: 'AT.png', t_url: 'Europe/Vienna'),
    WorldTime(location: 'Australia', flag: 'AU.png', t_url: 'Australia/Sydney'),
    WorldTime(location: 'Aruba', flag: 'AW.png', t_url: 'America/Aruba'),
    WorldTime(location: 'Åland Islands', flag: 'AX.png', t_url: 'Europe/Mariehamn'),
    WorldTime(location: 'Azerbaijan', flag: 'AZ.png', t_url: 'Asia/Baku'),
    WorldTime(location: 'Bosnia and Herzegovina', flag: 'BA.png', t_url: 'Europe/Sarajevo'),
    WorldTime(location: 'Barbados', flag: 'BB.png', t_url: 'America/Barbados'),
    WorldTime(location: 'Bangladesh', flag: 'BD.png', t_url: 'Asia/Dhaka'),
    WorldTime(location: 'Belgium', flag: 'BE.png', t_url: 'Europe/Brussels'),
    WorldTime(location: 'Burkina Faso', flag: 'BF.png', t_url: 'Africa/Ouagadougou'),
    WorldTime(location: 'Bulgaria', flag: 'BG.png', t_url: 'Europe/Sofia'),
    WorldTime(location: 'Bahrain', flag: 'BH.png', t_url: 'Asia/Bahrain'),
    WorldTime(location: 'Burundi', flag: 'BI.png', t_url: 'Africa/Bujumbura'),
    WorldTime(location: 'Benin', flag: 'BJ.png', t_url: 'Africa/Porto-Novo'),
    WorldTime(location: 'Saint Barthélemy', flag: 'BL.png', t_url: 'America/St_Barthelemy'),
    WorldTime(location: 'Bermuda', flag: 'BM.png', t_url: 'Atlantic/Bermuda'),
    WorldTime(location: 'Brunei Darussalam', flag: 'BN.png', t_url: 'Asia/Brunei'),
    WorldTime(location: 'Bolivia, Plurinational State of', flag: 'BO.png', t_url: 'America/La_Paz'),
    WorldTime(location: 'Caribbean Netherlands', flag: 'BQ.png', t_url: 'America/Kralendijk'),
    WorldTime(location: 'Brazil', flag: 'BR.png', t_url: 'America/Sao_Paulo'),
    WorldTime(location: 'Bahamas', flag: 'BS.png', t_url: 'America/Nassau'),
    WorldTime(location: 'Bhutan', flag: 'BT.png', t_url: 'Asia/Thimphu'),
    WorldTime(location: 'Bouvet Island', flag: 'BV.png', t_url: 'Africa/Addis_Ababa'),
    WorldTime(location: 'Botswana', flag: 'BW.png', t_url: 'Africa/Gaborone'),
    WorldTime(location: 'Belarus', flag: 'BY.png', t_url: 'Europe/Minsk'),
    WorldTime(location: 'Belize', flag: 'BZ.png', t_url: 'America/Belize'),
    WorldTime(location: 'Canada', flag: 'CA.png', t_url: 'America/Toronto'),
    WorldTime(location: 'Cocos (Keeling) Islands', flag: 'CC.png', t_url: 'Indian/Cocos'),
    WorldTime(location: 'Congo, the Democratic Republic of the', flag: 'CD.png', t_url: 'Africa/Kinshasa'),
    WorldTime(location: 'Central African Republic', flag: 'CF.png', t_url: 'Africa/Bangui'),
    WorldTime(location: 'Republic of the Congo', flag: 'CG.png', t_url: 'Africa/Brazzaville'),
    WorldTime(location: 'Switzerland', flag: 'CH.png', t_url: 'Europe/Zurich'),
    WorldTime(location: 'Côte d\'Ivoire', flag: 'CI.png', t_url: 'Africa/Abidjan'),
    WorldTime(location: 'Cook Islands', flag: 'CK.png', t_url: 'Pacific/Rarotonga'),
    WorldTime(location: 'Chile', flag: 'CL.png', t_url: 'America/Santiago'),
    WorldTime(location: 'Cameroon', flag: 'CM.png', t_url: 'Africa/Douala'),
    WorldTime(location: 'China (People\'s Republic of China)', flag: 'CN.png', t_url: 'Asia/Shanghai'),
    WorldTime(location: 'Colombia', flag: 'CO.png', t_url: 'America/Bogota'),
    WorldTime(location: 'Costa Rica', flag: 'CR.png', t_url: 'America/Costa_Rica'),
    WorldTime(location: 'Cuba', flag: 'CU.png', t_url: 'America/Havana'),
    WorldTime(location: 'Cape Verde', flag: 'CV.png', t_url: 'Atlantic/Cape_Verde'),
    WorldTime(location: 'Curaçao', flag: 'CW.png', t_url: 'America/Curacao'),
    WorldTime(location: 'Christmas Island', flag: 'CX.png', t_url: 'Indian/Christmas'),
    WorldTime(location: 'Cyprus', flag: 'CY.png', t_url: 'Asia/Nicosia'),
    WorldTime(location: 'Czech Republic', flag: 'CZ.png', t_url: 'Europe/Prague'),
    WorldTime(location: 'Germany', flag: 'DE.png', t_url: 'Europe/Berlin'),
    WorldTime(location: 'Djibouti', flag: 'DJ.png', t_url: 'Africa/Djibouti'),
    WorldTime(location: 'Denmark', flag: 'DK.png', t_url: 'Europe/Copenhagen'),
    WorldTime(location: 'Dominica', flag: 'DM.png', t_url: 'America/Dominica'),
    WorldTime(location: 'Dominican Republic', flag: 'DO.png', t_url: 'America/Santo_Domingo'),
    WorldTime(location: 'Algeria', flag: 'DZ.png', t_url: 'Africa/Algiers'),
    WorldTime(location: 'Ecuador', flag: 'EC.png', t_url: 'America/Guayaquil'),
    WorldTime(location: 'Estonia', flag: 'EE.png', t_url: 'Europe/Tallinn'),
    WorldTime(location: 'Egypt', flag: 'EG.png', t_url: 'Africa/Cairo'),
    WorldTime(location: 'Western Sahara', flag: 'EH.png', t_url: 'Africa/El_Aaiun'),
    WorldTime(location: 'Eritrea', flag: 'ER.png', t_url: 'Africa/Asmara'),
    WorldTime(location: 'Spain', flag: 'ES.png', t_url: 'Europe/Madrid'),
    WorldTime(location: 'Ethiopia', flag: 'ET.png', t_url: 'Africa/Addis_Ababa'),
    WorldTime(location: 'Europe', flag: 'EU.png', t_url: 'Europe/Berlin'),
    WorldTime(location: 'Finland', flag: 'FI.png', t_url: 'Europe/Helsinki'),
    WorldTime(location: 'Fiji', flag: 'FJ.png', t_url: 'Pacific/Fiji'),
    WorldTime(location: 'Falkland Islands (Malvinas)', flag: 'FK.png', t_url: 'Atlantic/Stanley'),
    WorldTime(location: 'Micronesia, Federated States of', flag: 'FM.png', t_url: 'Pacific/Chuuk'),
    WorldTime(location: 'Faroe Islands', flag: 'FO.png', t_url: 'Atlantic/Faroe'),
    WorldTime(location: 'France', flag: 'FR.png', t_url: 'Europe/Paris'),
    WorldTime(location: 'Gabon', flag: 'GA.png', t_url: 'Africa/Libreville'),
    WorldTime(location: 'Grenada', flag: 'GD.png', t_url: 'America/Grenada'),
    WorldTime(location: 'Georgia', flag: 'GE.png', t_url: 'Asia/Tbilisi'),
    WorldTime(location: 'French Guiana', flag: 'GF.png', t_url: 'America/Cayenne'),
    WorldTime(location: 'Guernsey', flag: 'GG.png', t_url: 'Europe/Guernsey'),
    WorldTime(location: 'Ghana', flag: 'GH.png', t_url: 'Africa/Accra'),
    WorldTime(location: 'Gibraltar', flag: 'GI.png', t_url: 'Europe/Gibraltar'),
    WorldTime(location: 'Greenland', flag: 'GL.png', t_url: 'America/Godthab'),
    WorldTime(location: 'Gambia', flag: 'GM.png', t_url: 'Africa/Banjul'),
    WorldTime(location: 'Guinea', flag: 'GN.png', t_url: 'Africa/Conakry'),
    WorldTime(location: 'Guadeloupe', flag: 'GP.png', t_url: 'America/Guadeloupe'),
    WorldTime(location: 'Equatorial Guinea', flag: 'GQ.png', t_url: 'Africa/Malabo'),
    WorldTime(location: 'Greece', flag: 'GR.png', t_url: 'Europe/Athens'),
    WorldTime(location: 'South Georgia and the South Sandwich Islands', flag: 'GS.png', t_url: 'Atlantic/South_Georgia'),
    WorldTime(location: 'Guatemala', flag: 'GT.png', t_url: 'America/Guatemala'),
    WorldTime(location: 'Guam', flag: 'GU.png', t_url: 'Pacific/Guam'),
    WorldTime(location: 'Guinea-Bissau', flag: 'GW.png', t_url: 'Africa/Bissau'),
    WorldTime(location: 'Guyana', flag: 'GY.png', t_url: 'America/Guyana'),
    WorldTime(location: 'Hong Kong', flag: 'HK.png', t_url: 'Asia/Hong_Kong'),
    WorldTime(location: 'Heard Island and McDonald Islands', flag: 'HM.png', t_url: 'Indian/Kerguelen'),
    WorldTime(location: 'Honduras', flag: 'HN.png', t_url: 'America/Tegucigalpa'),
    WorldTime(location: 'Croatia', flag: 'HR.png', t_url: 'Europe/Zagreb'),
    WorldTime(location: 'Haiti', flag: 'HT.png', t_url: 'America/Port-au-Prince'),
    WorldTime(location: 'Hungary', flag: 'HU.png', t_url: 'Europe/Budapest'),
    WorldTime(location: 'Indonesia', flag: 'ID.png', t_url: 'Asia/Jakarta'),
    WorldTime(location: 'Ireland', flag: 'IE.png', t_url: 'Europe/Dublin'),
    WorldTime(location: 'Israel', flag: 'IL.png', t_url: 'Asia/Jerusalem'),
    WorldTime(location: 'Isle of Man', flag: 'IM.png', t_url: 'Europe/Isle_of_Man'),
    WorldTime(location: 'India', flag: 'IN.png', t_url: 'Asia/Kolkata'),
    WorldTime(location: 'British Indian Ocean Territory', flag: 'IO.png', t_url: 'Indian/Chagos'),
    WorldTime(location: 'Iraq', flag: 'IQ.png', t_url: 'Asia/Baghdad'),
    WorldTime(location: 'Iran, Islamic Republic of', flag: 'IR.png', t_url: 'Asia/Tehran'),
    WorldTime(location: 'Iceland', flag: 'IS.png', t_url: 'Atlantic/Reykjavik'),
    WorldTime(location: 'Italy', flag: 'IT.png', t_url: 'Europe/Rome'),
    WorldTime(location: 'Jersey', flag: 'JE.png', t_url: 'Europe/Jersey'),
    WorldTime(location: 'Jamaica', flag: 'JM.png', t_url: 'America/Jamaica'),
    WorldTime(location: 'Jordan', flag: 'JO.png', t_url: 'Asia/Amman'),
    WorldTime(location: 'Japan', flag: 'JP.png', t_url: 'Asia/Tokyo'),
    WorldTime(location: 'Kenya', flag: 'KE.png', t_url: 'Africa/Nairobi'),
    WorldTime(location: 'Kyrgyzstan', flag: 'KG.png', t_url: 'Asia/Bishkek'),
    WorldTime(location: 'Cambodia', flag: 'KH.png', t_url: 'Asia/Phnom_Penh'),
    WorldTime(location: 'Kiribati', flag: 'KI.png', t_url: 'Pacific/Tarawa'),
    WorldTime(location: 'Comoros', flag: 'KM.png', t_url: 'Indian/Comoro'),
    WorldTime(location: 'Saint Kitts and Nevis', flag: 'KN.png', t_url: 'America/St_Kitts'),
    WorldTime(location: "Korea, Democratic People's Republic of", flag: 'KP.png', t_url: 'Asia/Pyongyang'),
    WorldTime(location: 'Korea, Republic of', flag: 'KR.png', t_url: 'Asia/Seoul'),
    WorldTime(location: 'Kuwait', flag: 'KW.png', t_url: 'Asia/Kuwait'),
    WorldTime(location: 'Cayman Islands', flag: 'KY.png', t_url: 'America/Cayman'),
    WorldTime(location: 'Kazakhstan', flag: 'KZ.png', t_url: 'Asia/Almaty'),
    WorldTime(location: "Laos (Lao People's Democratic Republic)", flag: 'LA.png', t_url: 'Asia/Vientiane'),
    WorldTime(location: 'Lebanon', flag: 'LB.png', t_url: 'Asia/Beirut'),
    WorldTime(location: 'Saint Lucia', flag: 'LC.png', t_url: 'America/St_Lucia'),
    WorldTime(location: 'Liechtenstein', flag: 'LI.png', t_url: 'Europe/Vaduz'),
    WorldTime(location: 'Sri Lanka', flag: 'LK.png', t_url: 'Asia/Colombo'),
    WorldTime(location: 'Liberia', flag: 'LR.png', t_url: 'Africa/Monrovia'),
    WorldTime(location: 'Lesotho', flag: 'LS.png', t_url: 'Africa/Maseru'),
    WorldTime(location: 'Lithuania', flag: 'LT.png', t_url: 'Europe/Vilnius'),
    WorldTime(location: 'Luxembourg', flag: 'LU.png', t_url: 'Europe/Luxembourg'),
    WorldTime(location: 'Latvia', flag: 'LV.png', t_url: 'Europe/Riga'),
    WorldTime(location: 'Libya', flag: 'LY.png', t_url: 'Africa/Tripoli'),
    WorldTime(location: 'Morocco', flag: 'MA.png', t_url: 'Africa/Casablanca'),
    WorldTime(location: 'Monaco', flag: 'MC.png', t_url: 'Europe/Monaco'),
    WorldTime(location: 'Moldova, Republic of', flag: 'MD.png', t_url: 'Europe/Chisinau'),
    WorldTime(location: 'Montenegro', flag: 'ME.png', t_url: 'Europe/Podgorica'),
    WorldTime(location: 'Saint Martin', flag: 'MF.png', t_url: 'America/Marigot'),
    WorldTime(location: 'Madagascar', flag: 'MG.png', t_url: 'Indian/Antananarivo'),
    WorldTime(location: 'Marshall Islands', flag: 'MH.png', t_url: 'Pacific/Majuro'),
    WorldTime(location: 'North Macedonia', flag: 'MK.png', t_url: 'Europe/Skopje'),
    WorldTime(location: 'Mali', flag: 'ML.png', t_url: 'Africa/Bamako'),
    WorldTime(location: 'Myanmar', flag: 'MM.png', t_url: 'Asia/Yangon'),
    WorldTime(location: 'Mongolia', flag: 'MN.png', t_url: 'Asia/Ulaanbaatar'),
    WorldTime(location: 'Macao', flag: 'MO.png', t_url: 'Asia/Macau'),
    WorldTime(location: 'Northern Mariana Islands', flag: 'MP.png', t_url: 'Pacific/Saipan'),
    WorldTime(location: 'Martinique', flag: 'MQ.png', t_url: 'America/Martinique'),
    WorldTime(location: 'Mauritania', flag: 'MR.png', t_url: 'Africa/Nouakchott'),
    WorldTime(location: 'Montserrat', flag: 'MS.png', t_url: 'America/Montserrat'),
    WorldTime(location: 'Malta', flag: 'MT.png', t_url: 'Europe/Malta'),
    WorldTime(location: 'Mauritius', flag: 'MU.png', t_url: 'Indian/Mauritius'),
    WorldTime(location: 'Maldives', flag: 'MV.png', t_url: 'Indian/Maldives'),
    WorldTime(location: 'Malawi', flag: 'MW.png', t_url: 'Africa/Blantyre'),
    WorldTime(location: 'Mexico', flag: 'MX.png', t_url: 'America/Mexico_City'),
    WorldTime(location: 'Malaysia', flag: 'MY.png', t_url: 'Asia/Kuala_Lumpur'),
    WorldTime(location: 'Mozambique', flag: 'MZ.png', t_url: 'Africa/Maputo'),
    WorldTime(location: 'Namibia', flag: 'NA.png', t_url: 'Africa/Windhoek'),
    WorldTime(location: 'New Caledonia', flag: 'NC.png', t_url: 'Pacific/Noumea'),
    WorldTime(location: 'Niger', flag: 'NE.png', t_url: 'Africa/Niamey'),
    WorldTime(location: 'Norfolk Island', flag: 'NF.png', t_url: 'Pacific/Norfolk'),
    WorldTime(location: 'Nigeria', flag: 'NG.png', t_url: 'Africa/Lagos'),
    WorldTime(location: 'Nicaragua', flag: 'NI.png', t_url: 'America/Managua'),
    WorldTime(location: 'Netherlands', flag: 'NL.png', t_url: 'Europe/Amsterdam'),
    WorldTime(location: 'Norway', flag: 'NO.png', t_url: 'Europe/Oslo'),
    WorldTime(location: 'Nepal', flag: 'NP.png', t_url: 'Asia/Kathmandu'),
    WorldTime(location: 'Nauru', flag: 'NR.png', t_url: 'Pacific/Nauru'),
    WorldTime(location: 'Niue', flag: 'NU.png', t_url: 'Pacific/Niue'),
    WorldTime(location: 'New Zealand', flag: 'NZ.png', t_url: 'Pacific/Auckland'),
    WorldTime(location: 'Oman', flag: 'OM.png', t_url: 'Asia/Muscat'),
    WorldTime(location: 'Panama', flag: 'PA.png', t_url: 'America/Panama'),
    WorldTime(location: 'Peru', flag: 'PE.png', t_url: 'America/Lima'),
    WorldTime(location: 'French Polynesia', flag: 'PF.png', t_url: 'Pacific/Tahiti'),
    WorldTime(location: 'Papua New Guinea', flag: 'PG.png', t_url: 'Pacific/Port_Moresby'),
    WorldTime(location: 'Philippines', flag: 'PH.png', t_url: 'Asia/Manila'),
    WorldTime(location: 'Pakistan', flag: 'PK.png', t_url: 'Asia/Karachi'),
    WorldTime(location: 'Poland', flag: 'PL.png', t_url: 'Europe/Warsaw'),
    WorldTime(location: 'Saint Pierre and Miquelon', flag: 'PM.png', t_url: 'America/Miquelon'),
    WorldTime(location: 'Pitcairn', flag: 'PN.png', t_url: 'Pacific/Pitcairn'),
    WorldTime(location: 'Puerto Rico', flag: 'PR.png', t_url: 'America/Puerto_Rico'),
    WorldTime(location: 'Palestine', flag: 'PS.png', t_url: 'Asia/Gaza'),
    WorldTime(location: 'Portugal', flag: 'PT.png', t_url: 'Europe/Lisbon'),
    WorldTime(location: 'Palau', flag: 'PW.png', t_url: 'Pacific/Palau'),
    WorldTime(location: 'Paraguay', flag: 'PY.png', t_url: 'America/Asuncion'),
    WorldTime(location: 'Qatar', flag: 'QA.png', t_url: 'Asia/Qatar'),
    WorldTime(location: 'Réunion', flag: 'RE.png', t_url: 'Indian/Reunion'),
    WorldTime(location: 'Romania', flag: 'RO.png', t_url: 'Europe/Bucharest'),
    WorldTime(location: 'Serbia', flag: 'RS.png', t_url: 'Europe/Belgrade'),
    WorldTime(location: 'Russian Federation', flag: 'RU.png', t_url: 'Europe/Moscow'),
    WorldTime(location: 'Rwanda', flag: 'RW.png', t_url: 'Africa/Kigali'),
    WorldTime(location: 'Saudi Arabia', flag: 'SA.png', t_url: 'Asia/Riyadh'),
    WorldTime(location: 'Solomon Islands', flag: 'SB.png', t_url: 'Pacific/Guadalcanal'),
    WorldTime(location: 'Seychelles', flag: 'SC.png', t_url: 'Indian/Mahe'),
    WorldTime(location: 'Sudan', flag: 'SD.png', t_url: 'Africa/Khartoum'),
    WorldTime(location: 'Sweden', flag: 'SE.png', t_url: 'Europe/Stockholm'),
    WorldTime(location: 'Singapore', flag: 'SG.png', t_url: 'Asia/Singapore'),
    WorldTime(location: 'Saint Helena, Ascension and Tristan da Cunha', flag: 'SH.png', t_url: 'Atlantic/St_Helena'),
    WorldTime(location: 'Slovenia', flag: 'SI.png', t_url: 'Europe/Ljubljana'),
    WorldTime(location: 'Svalbard and Jan Mayen Islands', flag: 'SJ.png', t_url: 'Arctic/Longyearbyen'),
    WorldTime(location: 'Slovakia', flag: 'SK.png', t_url: 'Europe/Bratislava'),
    WorldTime(location: 'Sierra Leone', flag: 'SL.png', t_url: 'Africa/Freetown'),
    WorldTime(location: 'San Marino', flag: 'SM.png', t_url: 'Europe/San_Marino'),
    WorldTime(location: 'Senegal', flag: 'SN.png', t_url: 'Africa/Dakar'),
    WorldTime(location: 'Somalia', flag: 'SO.png', t_url: 'Africa/Mogadishu'),
    WorldTime(location: 'Suriname', flag: 'SR.png', t_url: 'America/Paramaribo'),
    WorldTime(location: 'South Sudan', flag: 'SS.png', t_url: 'Africa/Juba'),
    WorldTime(location: 'Sao Tome and Principe', flag: 'ST.png', t_url: 'Africa/Sao_Tome'),
    WorldTime(location: 'El Salvador', flag: 'SV.png', t_url: 'America/El_Salvador'),
    WorldTime(location: 'Sint Maarten (Dutch part)', flag: 'SX.png', t_url: 'America/Lower_Princes'),
    WorldTime(location: 'Syrian Arab Republic', flag: 'SY.png', t_url: 'Asia/Damascus'),
    WorldTime(location: 'Swaziland', flag: 'SZ.png', t_url: 'Africa/Mbabane'),
    WorldTime(location: 'Turks and Caicos Islands', flag: 'TC.png', t_url: 'America/Grand_Turk'),
    WorldTime(location: 'Chad', flag: 'TD.png', t_url: 'Africa/Ndjamena'),
    WorldTime(location: 'French Southern Territories', flag: 'TF.png', t_url: 'Indian/Kerguelen'),
    WorldTime(location: 'Togo', flag: 'TG.png', t_url: 'Africa/Lome'),
    WorldTime(location: 'Thailand', flag: 'TH.png', t_url: 'Asia/Bangkok'),
    WorldTime(location: 'Tajikistan', flag: 'TJ.png', t_url: 'Asia/Dushanbe'),
    WorldTime(location: 'Tokelau', flag: 'TK.png', t_url: 'Pacific/Fakaofo'),
    WorldTime(location: 'Timor-Leste', flag: 'TL.png', t_url: 'Asia/Dili'),
    WorldTime(location: 'Turkmenistan', flag: 'TM.png', t_url: 'Asia/Ashgabat'),
    WorldTime(location: 'Tunisia', flag: 'TN.png', t_url: 'Africa/Tunis'),
    WorldTime(location: 'Tonga', flag: 'TO.png', t_url: 'Pacific/Tongatapu'),
    WorldTime(location: 'Turkey', flag: 'TR.png', t_url: 'Europe/Istanbul'),
    WorldTime(location: 'Trinidad and Tobago', flag: 'TT.png', t_url: 'America/Port_of_Spain'),
    WorldTime(location: 'Tuvalu', flag: 'TV.png', t_url: 'Pacific/Funafuti'),
    WorldTime(location: 'Taiwan (Republic of China)', flag: 'TW.png', t_url: 'Asia/Taipei'),
    WorldTime(location: 'Tanzania, United Republic of', flag: 'TZ.png', t_url: 'Africa/Dar_es_Salaam'),
    WorldTime(location: 'Ukraine', flag: 'UA.png', t_url: 'Europe/Kiev'),
    WorldTime(location: 'Uganda', flag: 'UG.png', t_url: 'Africa/Kampala'),
    WorldTime(location: 'US Minor Outlying Islands', flag: 'UM.png', t_url: 'Pacific/Midway'),
    WorldTime(location: 'United States', flag: 'US.png', t_url: 'America/New_York'),
    WorldTime(location: 'Uruguay', flag: 'UY.png', t_url: 'America/Montevideo'),
    WorldTime(location: 'Uzbekistan', flag: 'UZ.png', t_url: 'Asia/Samarkand'),
    WorldTime(location: 'Holy See (Vatican City State)', flag: 'VA.png', t_url: 'Europe/Vatican'),
    WorldTime(location: 'Saint Vincent and the Grenadines', flag: 'VC.png', t_url: 'America/St_Vincent'),
    WorldTime(location: 'Venezuela, Bolivarian Republic of', flag: 'VE.png', t_url: 'America/Caracas'),
    WorldTime(location: 'Virgin Islands, British', flag: 'VG.png', t_url: 'America/Tortola'),
    WorldTime(location: 'Virgin Islands, U.S.', flag: 'VI.png', t_url: 'America/St_Thomas'),
    WorldTime(location: 'Vietnam', flag: 'VN.png', t_url: 'Asia/Ho_Chi_Minh'),
    WorldTime(location: 'Vanuatu', flag: 'VU.png', t_url: 'Pacific/Efate'),
    WorldTime(location: 'Wallis and Futuna Islands', flag: 'WF.png', t_url: 'Pacific/Wallis'),
    WorldTime(location: 'Samoa', flag: 'WS.png', t_url: 'Pacific/Apia'),
    WorldTime(location: 'Kosovo', flag: 'XK.png', t_url: 'Europe/Pristina'),
    WorldTime(location: 'Yemen', flag: 'YE.png', t_url: 'Asia/Aden'),
    WorldTime(location: 'Mayotte', flag: 'YT.png', t_url: 'Indian/Mayotte'),
    WorldTime(location: 'South Africa', flag: 'ZA.png', t_url: 'Africa/Johannesburg'),
    WorldTime(location: 'Zambia', flag: 'ZM.png', t_url: 'Africa/Lusaka'),
    WorldTime(location: 'Zimbabwe', flag: 'ZW.png', t_url: 'Africa/Harare')

  ];

void updateTime(index) async{
  WorldTime instance =  locations[index];

  await instance.getTime();

  Navigator.pop(context, {
    'location' : instance.location,
    'time' : instance.time,
    'flag': instance.flag.toLowerCase(),
    'isDayTime' :instance.isDayTime,
  });

}

  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text('edit location'),
        centerTitle: true,
        elevation: 0,
      ),
      body: ListView.builder(
         itemCount: locations.length,
          itemBuilder: (context,index){
           return Padding(
             padding: const EdgeInsets.symmetric(vertical: 1.0,horizontal: 2.0),
             child: Card(
               child: ListTile(
                 title: Text(locations[index].location),
                 onTap: (){
                   updateTime(index);
                 },
                 leading: CircleAvatar(
                   backgroundImage: AssetImage('assets/${locations[index].flag.toLowerCase()}'),
                 ),
               ),
             ),
           );

          }
      ),
    );
  }
}
